.gitignore
app/Area.php
app/Exam.php
app/Http/Controllers/AreasController.php
app/Http/Controllers/ExamsController.php
app/Http/Controllers/ModulesController.php
app/Http/Controllers/RollOfListsController.php
app/Http/Controllers/SchoolCyclesController.php
app/Http/Controllers/SubjectsController.php
app/Http/Controllers/TasksController.php
app/Module.php
app/RollOfList.php
app/SchoolCycle.php
app/Subject.php
app/Task.php
app/User.php
database/migrations/2018_01_15_131515_create_school_cycles_table.php
database/migrations/2018_01_15_133249_create_areas_table.php
database/migrations/2018_01_15_133407_create_subjects_table.php
database/migrations/2018_01_15_133935_create_exams_table.php
database/migrations/2018_01_15_134326_create_modules_table.php
database/migrations/2018_01_15_134452_create_roll_of_lists_table.php
database/migrations/2018_01_15_140826_create_tasks_table.php

Requerimiento 1: Migraciones, Modelos y Controladores, referente a ciclos escolares.

Requirement1

---

app/Conversation.php
app/Http/Controllers/ConversationsController.php
app/Http/Controllers/GroupsController.php
app/Http/Controllers/ItemsConversationsController.php
app/ItemConversation.php
database/migrations/2018_01_27_000530_create_conversations_table.php
database/migrations/2018_01_27_001408_create_items_conversations_table.php
resources/views/groups.blade.php
routes/web.php

Se agregan nuevas migraciones, para añadir las tablas para el uso de comentarios.-
Se pueden escribir comentarios en groups y estos se almacenarán.-
Añadida nueva ruta para almacenar los comentarios.-

Cambios para los comentarios y para ver los miembros del grupo

---

app/Http/Controllers/AreasController.php
app/Http/Controllers/SchoolCyclesController.php
app/Http/Controllers/SubjectsController.php
composer.json
resources/views/area.blade.php
resources/views/schoolcycles.blade.php
resources/views/subjects.blade.php
routes/web.php

Añadiendo nueva ruta y quitando extensión del composer.json.-

Incorporando comentarios en Area, Asignatura, Ciclo Escolar.- 

---

app/Http/Controllers/ApplyExamsController.php
app/Http/Controllers/ExamsController.php
resources/views/takeexam.blade.php
resources/views/test.blade.php
routes/web.php

Correcciones a la vista previa del examen.- Correcciones al examen al presentar, tanto visual como internamente para poder controlar el envío de las respuestas.- Almacenamiento de las respuestas al examen.-

Lo relacionado a ver correctamente el examen y almacenar las respuestas

---

resources/views/takeexam.blade.php
resources/views/test.blade.php

Ajustando tamaño etiqueta para las respuestas.- Identando código.-

Ajustando tamaño etiqueta para las respuestas.-

---

app/Http/Controllers/ApplyExamsController.php
resources/views/takeexam.blade.php
resources/views/test.blade.php

Correcciones para guardar las respuestas.- Colocando tabla en español.- Quitando botón regresar del examen.-

Correcciones al examen

---

app/ApplyExam.php
app/ApplyTask.php
app/Group.php
app/Http/Controllers/ApplyExamsController.php
app/Http/Controllers/ApplyTasksController.php
app/Http/Controllers/ResultsController.php
app/Http/Controllers/ResultsItemsController.php
app/Http/Controllers/TasksController.php
app/Result.php
app/ResultItem.php
app/Task.php
database/migrations/2018_02_27_210329_add_new_fields_tasks_table.php
database/migrations/2018_02_27_231656_create_apply_tasks_table.php
database/migrations/2018_03_01_003143_create_results_table.php
database/migrations/2018_03_01_003550_create_results_items_table.php
resources/views/area.blade.php
resources/views/groups.blade.php
resources/views/profile.blade.php
resources/views/results.blade.php
resources/views/schoolcycles.blade.php
resources/views/subjects.blade.php
resources/views/takeeval.blade.php
resources/views/task.blade.php
resources/views/test.blade.php
routes/web.php

guardando las respuestas de tareas/examenes y mostrando sus resultados

Resultados de tareas y examenes

---

resources/views/groups.blade.php
resources/views/layouts/app.blade.php
resources/views/leftmenu.blade.php
resources/views/subjects.blade.php
resources/views/task.blade.php
resources/views/test.blade.php

Manteniendo desplegado el submenu

Manipulando class active en el menu izquierdo.- agregando title en groups.-

---

app/Http/Controllers/ConfigurationsController.php
app/Http/Controllers/UsersController.php
composer.json
composer.lock
resources/views/configurations.blade.php
resources/views/profile.blade.php
routes/web.php

Agregando librería requerida doctrine/dbal.- Agregando configuración de perfil, que permite agregar nuevos campos a la tabla Users.- Creando la vista configurations.- Editando el perfil para mostrar los nuevos campos que se inserten.- Agregando nuevas rutas.-

parte del rq9

---

app/Column.php
app/Http/Controllers/Auth/RegisterController.php
app/Http/Controllers/ConfigurationsController.php
app/Http/Controllers/UsersController.php
app/Inscription.php
app/User.php
database/migrations/2018_03_13_044859_add_inscription_id_to_users_table.php
database/migrations/2018_03_13_211400_create_columns_table.php
database/migrations/2018_03_13_212352_create_inscriptions_table.php
resources/views/configurations.blade.php
resources/views/layouts/app.blade.php
resources/views/profile.blade.php
routes/web.php

Incorporados 2 nuevos modelos y sus migraciones, para el control de las columnas y del proceso de inscripcion.- Agregado el campo inscription_id en User.- Modificada la ruta de acceso al Register.-

Modificaciones para poder crear nuevas columnas en la tabla Users.- 

---

app/Http/Controllers/Auth/RegisterController.php
app/Http/Controllers/ConfigurationsController.php
resources/views/auth/register.blade.php
resources/views/configurations.blade.php

Permite el registro de usuarios segun el proceso de inscripcion.-

Permite el registro de procesos de inscripcion.-

---

app/Http/Controllers/UsersController.php
resources/views/auth/register.blade.php
resources/views/configurations.blade.php
resources/views/home.blade.php
resources/views/layouts/app.blade.php
resources/views/leftmenu.blade.php
resources/views/profile.blade.php
resources/views/task.blade.php
resources/views/test.blade.php

Ajustes para mostrar información en el perfil según los datos adicionales que correspondan.-

---

app/Http/Controllers/AreasController.php
app/Http/Controllers/ArticlesController.php
app/Http/Controllers/ExamsController.php
app/Http/Controllers/ForumsController.php
app/Http/Controllers/GroupsController.php
app/Http/Controllers/LinksController.php
app/Http/Controllers/ModulesController.php
app/Http/Controllers/SubjectsController.php
app/Http/Controllers/TasksController.php
resources/views/area.blade.php
resources/views/articles.blade.php
resources/views/forums.blade.php
resources/views/groups.blade.php
resources/views/layouts/_table_related.blade.php
resources/views/leftmenu.blade.php
resources/views/modules.blade.php
resources/views/schoolcycles.blade.php
resources/views/subjects.blade.php
resources/views/task.blade.php
resources/views/test.blade.php
routes/web.php

Modificacion para que al terminar un registro se haga show del registro almacenado.- eliminados elementos en Modules y agregado el onchange de redireccion.-

funcionalidad para el agregar registros desde la pestañas de elementos relacionados.-

---

app/Conversation.php
app/Forum.php
app/Http/Controllers/ForumsController.php
app/Http/Controllers/QuestionsForumsController.php
app/Http/Controllers/VotesController.php
app/Http/Controllers/WallsController.php
app/QuestionForum.php
app/Vote.php
composer.json
composer.lock
config/app.php
database/migrations/2018_04_19_225437_create_questions_forums_table.php
database/migrations/2018_04_19_225555_create_votes_table.php
resources/views/forums.blade.php
resources/views/layouts/_modal_confirmation_delete.blade.php
resources/views/layouts/_table_related.blade.php
resources/views/results.blade.php
resources/views/walls.blade.php
routes/web.php

Los Post del muro ahora se realizan desde un Modal, se puede eliminar un Muro, adaptación al muro según el dispositivo donde se acceda móvil-tablet / pc.
Modificaciones al Foro, permite agregar preguntas, responder preguntas, votar por las preguntas y se puede eliminar el foro.

Modificaciones a Muro y Foro

---

app/Http/Controllers/ForumsController.php
app/Http/Controllers/HomeController.php
resources/views/forums.blade.php
resources/views/layouts/_modal_global_search.blade.php
resources/views/layouts/app.blade.php
resources/views/topmenu.blade.php
resources/views/walls.blade.php
routes/web.php

Ordenar las preguntas por cantidad de votos en el Foro.-
Busqueda Global.-
Moviendo boton eliminar del muro.-

Cambios varios

---

resources/views/layouts/app.blade.php
resources/views/walls.blade.php

Agregando validación para cuando no hay resultados en la búsqueda global.-

Corrección para eliminar al cambiar el botón en el muro.- 

---

app/Http/Controllers/FullCourseController.php
public/inspinia/css/style.css
resources/views/fullcourse.blade.php
resources/views/layouts/app.blade.php
routes/web.php

Terminando Wizard, agregado punto 5 para elegir que funcionalidad tendrán las asignaturas que seleccione el usuario de las que se están generando.- Validaciones completas, si en pasos previos se elimina un área o una asignatura.-

Terminando Wizard, agregado punto 5 para elegir que funcionalidad tendrán las asignaturas que seleccione el usuario de las que se están generando

---

app/Http/Controllers/ConfigurationsController.php
app/Http/Controllers/WizardsController.php
public/inspinia/css/plugins/toastr/toastr.min.css
resources/views/area.blade.php
resources/views/articles.blade.php
resources/views/configurations.blade.php
resources/views/forums.blade.php
resources/views/layouts/_script_spinner_code.blade.php
resources/views/layouts/app.blade.php
resources/views/links.blade.php
resources/views/list.blade.php
resources/views/modules.blade.php
resources/views/profile.blade.php
resources/views/results.blade.php
resources/views/schoolcycles.blade.php
resources/views/subjects.blade.php
resources/views/takeeval.blade.php
resources/views/task.blade.php
resources/views/test.blade.php
resources/views/walls.blade.php
resources/views/wizards.blade.php
routes/web.php

Culminando todo lo relacionado al requerimiento 17

Requerimiento 17

---

app/Http/Controllers/HomeController.php
app/Http/Controllers/SchoolCyclesController.php
app/Http/Controllers/WizardsController.php
database/migrations/2018_07_06_035912_add_start_end_date_to_school_cycles.php
resources/views/area.blade.php
resources/views/articles.blade.php
resources/views/forums.blade.php
resources/views/groups.blade.php
resources/views/home_master.blade.php
resources/views/layouts/_conversations.blade.php
resources/views/links.blade.php
resources/views/modules.blade.php
resources/views/profile.blade.php
resources/views/schoolcycles.blade.php
resources/views/subjects.blade.php
resources/views/test.blade.php
resources/views/topmenu.blade.php
resources/views/walls.blade.php
resources/views/wizards.blade.php

Agregando datos en el inicio de usuario Master.- Colocando imágenes de avatar circulares.- Agregando start_date y end_date de Curso en formato fecha.-

Requerimiento 18

---

app/Favorite.php
app/Http/Controllers/FavoritesController.php
app/Http/Controllers/ItemsConversationsController.php
app/ItemConversation.php
app/User.php
database/migrations/2018_07_21_210300_create_favorites_table.php
public/inspinia/css/style.css
resources/views/forums.blade.php
resources/views/layouts/_conversations.blade.php
resources/views/layouts/app.blade.php
resources/views/topmenu.blade.php
resources/views/walls.blade.php
routes/web.php

- Colocando en mayúsculas la E, al eliminar un comentario con respuestas.
- Ajustando comentarios mas del 50% de conversaciones eliminadas y se borra la conversación completa.
- Agregando funcionalidad de lugares Favoritos de manera global.

Funcionalidad de eliminar comentarios y lugares favoritos

---

app/Http/Controllers/ArticlesController.php
app/Http/Controllers/ItemsConversationsController.php
app/Http/Controllers/UsersController.php
app/Http/Controllers/WallsController.php
public/inspinia/css/style.css
resources/views/articles.blade.php
resources/views/layouts/_script_comentarios_guest.blade.php
resources/views/leftmenu.blade.php
resources/views/topmenu.blade.php
resources/views/walls.blade.php
routes/web.php

Comentarios en el muro, eliminar publicaciones y comentarios.-
Los Artículos pueden ser vistos por invitados.-
Los invitados pueden dejar comentarios y eliminarlos (en el momento, es decir, sin recargar la pagina).- 
Mejoras en Favorites.- 
Agrupando codigo en un componente reutilizable.-

Permitir visitantes y comentarios en muro y articulos
